image: ubuntu:17.04

before_script:
  - apt -yy update && apt -yy install ansible python-openstackclient python-shade openssh-client
  - mkdir -p ~/.ssh
  - mkdir -p ~/.config/openstack
  - "echo -e \"clouds:\\n  sandbox:\\n    region_name: RegionOne\\n    auth:\\n      username: $OS_USERNAME\\n      password: $OS_PASSWORD\\n      project_name: $OS_PROJECT_NAME\\n      auth_url: $OS_AUTH_URL\" > ~/.config/openstack/clouds.yaml"

stages:
  - test
  - deploy
  - cleanup

test:
  stage: test
  script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check site.yaml
    - ansible-playbook --syntax-check cleanup.yaml

deploy:
  stage: deploy
  script:
    - ansible-playbook site.yaml

cleanup:
  stage: cleanup
  script:
    - ansible-playbook cleanup.yaml
