image: ubuntu:17.04

before_script:
  - apt -yy update && apt -yy install ansible python-openstackclient python-shade
	- mkdir -p ~/.config/openstack
  - >
cat << EOF > ~/.config/openstack/clouds.yaml
clouds:
  sandbox:
    region_name: RegionOne
    auth:
      username: $OS_USERNAME
      password: $OS_PASSWORD
      project_name: $OS_PROJECT_NAME
      auth_url: $OS_AUTH_URL
EOF

stages:
  - test
  - deploy
  - cleanup

test:
  stage: test
  script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check site.yaml
    - ansible-playbook --syntax-check cleanup.yaml

deploy:
  stage: deploy
  script:
    - ansible-playbook site.yaml

cleanup:
  stage: cleanup
  script:
    - ansible-playbook cleanup.yaml
