image: ubuntu:17.04

before_script:
  - apt -yy update && apt -yy install ansible python-openstackclient python-shade openssh-client python-pip

stages:
  - syntax
  - test

syntax:
  stage: syntax
  script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check site.yaml

lint:
  state: syntax
  script:
    - pip2 install ansible-lint
    - ansible-lint site.yaml
  allow_failure: true

test:
  stage: test
  script:
    - mkdir -p ~/.config/openstack
    - "echo -e \"clouds:\\n  sandbox:\\n    region_name: RegionOne\\n    auth:\\n      username: $OS_USERNAME\\n      password: $OS_PASSWORD\\n      project_name: $OS_PROJECT_NAME\\n      auth_url: $OS_AUTH_URL\" > ~/.config/openstack/clouds.yaml"
    - mkdir -p ~/.ssh
    - ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
    - openstack --os-cloud sandbox keypair delete gitlab-ci || true
    - openstack --os-cloud sandbox keypair create --public-key ~/.ssh/id_rsa.pub gitlab-ci
    - ansible-playbook site.yaml
    - ansible-playbook site.yaml -e state=absent
