image: ubuntu:17.04

before_script:
  - apt -yy update && apt -yy install ansible python-openstackclient

stages:
  - test
  - deploy
  - cleanup

test:
  stage: test
  script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check site.yaml
    - ansible-playbook --syntax-check cleanup.yaml

deploy:
  stage: deploy
  script:
    - ansible-playbook site.yaml

cleanup:
  stage: cleanup
  script:
    - ansible-playbook cleanup.yaml
