image: gitlab.infraly.ch:4567/francois/docker-ansible:master

stages:
  - syntax
  - test

syntax:
  stage: syntax
  script:
    - ansible-playbook --version
    - ansible-playbook --syntax-check site.yaml

lint:
  stage: syntax
  script:
    - ansible-lint site.yaml
  allow_failure: true

test:
  stage: test
  script:
    - printenv
    - mkdir -p ~/.config/openstack
    - "echo -e \"clouds:\\n  sandbox:\\n    region_name: RegionOne\\n    auth:\\n      username: $OS_USERNAME\\n      password: $OS_PASSWORD\\n      project_name: $OS_PROJECT_NAME\\n      auth_url: $OS_AUTH_URL\" > ~/.config/openstack/clouds.yaml"
    - mkdir -p ~/.ssh
    - ssh-keygen -t rsa -P "" -f ~/.ssh/id_rsa
    - openstack --os-cloud sandbox keypair delete gitlab-ci-$CI_BUILD_ID || true
    - openstack --os-cloud sandbox keypair create --public-key ~/.ssh/id_rsa.pub gitlab-ci-$CI_BUILD_ID
    - sed -i -e "s/gitlab-ci/k8s-gitlab-ci-$CI_BUILD_ID/g" group_vars/all.yaml
    - ansible-playbook site.yaml
  after_script:
    - ansible-playbook site.yaml -e state=absent
