---
- name: Destroy k8s nodes
  hosts: localhost
  vars_files:
    - vars.yaml
  tasks:
  - os_server:
      cloud: "{{ cloud }}"
      state: absent
      name: "k8s-{{ item }}"
    with_sequence: count="{{ node_count }}"

  - os_security_group:
      cloud: "{{ cloud }}"
      name: "sg-{{ name }}"
      state: absent
