---
- name: Launch k8s nodes
  hosts: localhost
  roles:
    - instances

- name: Node preparation
  hosts: nodes
  tags:
    - bootstrap
  gather_facts: false
  roles:
    - common

- name: Install repo and packages
  hosts: nodes
  tags:
    - bootstrap
  become: true
  roles:
    - kubeadm

- name: k8s master setup
  hosts: nodes[0]
  tags:
    - bootstrap
  become: true
  roles:
    - kubeadm-master

- name: k8s minions setup
  hosts: nodes[1:]
  become: true
  tags:
    - bootstrap
  roles:
    - kubeadm-nodes

- name: k8s addons
  hosts: nodes[0]
  tags:
    - bootstrap
  become: true
  roles:
    - k8s-addons

- name: Health check
  hosts: nodes[0]
  become: true
  roles:
    - healthcheck

- name: Local kubectl configuration
  hosts: localhost
  roles:
    - kubectl
