---
- name: Launch k8s nodes
  hosts: localhost
  tasks:
  - name: Get cloud configuration
    os_client_config:
      clouds:
        - "{{ cloud }}"

  - name: Create security group before instances
    os_security_group:
      cloud: "{{ cloud }}"
      name: "sg-{{ name }}"
      state: present
    when: state == "present"

  - name: Open security group from anywhere
    os_security_group_rule:
      cloud: "{{ cloud }}"
      security_group: "sg-{{ name }}"
      remote_ip_prefix: 0.0.0.0/0
    when: state == "present"

  - name: Open security group from inside the cluster
    os_security_group_rule:
      cloud: "{{ cloud }}"
      security_group: "sg-{{ name }}"
      remote_group: "sg-{{ name }}"
    when: state == "present"

  - name: Create OpenStack instance
    os_server:
      cloud: "{{ cloud }}"
      security_groups: "sg-{{ name }}"
      state: "{{ state }}"
      name: "{{ name }}-{{ item }}"
      image: "{{ image }}"
      key_name: "{{ key_name }}"
      flavor_ram: "{{ node_memory }}"
      nics:
        - net-name: "{{ network|default(omit) }}"
      floating_ip_pools: "{{ floating_ip_pool|default(omit) }}"
      userdata: |
        #cloud-config
        package_upgrade: true
    register: "nodes"
    with_sequence: count="{{ node_count }}"

  - name: Delete security group
    os_security_group:
      cloud: "{{ cloud }}"
      name: "sg-{{ name }}"
      state: absent
    when: state == "absent"

  - name: Update inventory
    add_host:
      name: "{{ item.server.name }}"
      ansible_ssh_host: "{{ item.server.interface_ip }}"
      ansible_ssh_user: ubuntu
      groupname: nodes
    with_items: "{{ nodes.results }}"
    when: state == "present"

  - name: Wait during instances boot
    wait_for:
      host: "{{ item.server.interface_ip }}"
      port: 22
      search_regex: OpenSSH
    with_items: "{{ nodes.results }}"
    when: state == "present"

  - name: Allow SSH keys on first connection
    shell: "ssh-keyscan {{ item.server.interface_ip }} >> ~/.ssh/known_hosts"
    with_items: "{{ nodes.results }}"
    when: state == "present"

- name: Node preparation
  hosts: nodes
  gather_facts: false

  pre_tasks:
    - name: Wait for cloud-init to finish
      raw: while ! test -f /var/lib/cloud/instance/boot-finished; do sleep 1; done
      tags:
        - skip_ansible_lint

    # http://stackoverflow.com/questions/32429259/ansible-fails-with-bin-sh-1-usr-bin-python-not-found
    - name: install ansible requirements
      raw: /usr/bin/test -f /usr/bin/python || sudo apt-get update && sudo apt-get -y install python-simplejson
      tags:
        - skip_ansible_lint

    - name: Setup
      action: setup

- name: Install repo and packages
  hosts: nodes
  become: true
  tasks:
    - name: Install k8s APT repo GPG key
      apt_key:
        url: 'https://packages.cloud.google.com/apt/doc/apt-key.gpg'
        state: present

    - name: Setup k8s APT repo
      apt_repository:
        repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install docker and kubernetes packages
      apt:
        name: "{{item}}"
        state: installed
        update_cache: yes
      with_items:
        - docker.io
        - kubelet
        - kubeadm
        - kubectl
        - kubernetes-cni

    - name: add hosts
      lineinfile:
        dest: "/etc/hosts"
        regexp: ".*{{ hostvars[item].ansible_hostname }}$"
        line: "{{ hostvars[item].ansible_default_ipv4.address }} {{ hostvars[item].ansible_hostname }}"
        state: present
      when: hostvars[item].ansible_hostname is defined
      with_items: "{{groups['all'] | default([])}}"

    - name: Create OpenStack cloud configuration
      template:
        src: files/cloud-config.j2
        dest: /etc/kubernetes/cloud-config
        mode: 0600

    - name: Override default kubeadm configuration to use the OpenStack cloud configuration
      copy:
        src: files/10-kubeadm.conf
        dest: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
        mode: 0600
      notify:
        - Restart kubelet

  handlers:
    - name: Restart kubelet
      systemd:
        state: restarted
        daemon_reload: yes
        name: kubelet

- name: k8s cluster setup
  hosts: nodes
  become: true
  tasks:
    # Master
    - name: Check for existing kubelet configuration
      stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: kubeadm token generate
      command: kubeadm token generate
      register: token1
      when: inventory_hostname == groups.nodes[0] and kubelet_conf.stat.exists == False

    - name: kubeadm get existing token
      command: sh -c '/usr/bin/kubectl -n kube-system get secret clusterinfo -o yaml | grep token-map | awk "{print \$2}" | base64 -d | sed "s|{||g;s|}||g;s|:|.|g;s/\"//g;" | xargs echo'
      register: token2
      when: inventory_hostname == groups.nodes[0] and kubelet_conf.stat.exists == True

    # https://github.com/ansible/ansible/issues/4297
    - name: token
      set_fact:
        token: "{{ token1 if inventory_hostname == groups.nodes[0] and kubelet_conf.stat.exists == False else token2 }}"

    - name: kubeadm init
      command: "kubeadm init --cloud-provider openstack --token {{ token.stdout }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: inventory_hostname == groups.nodes[0]

    # Minions
    - name: kubeadm join
      command: "kubeadm join --skip-preflight-checks --token {{ hostvars[groups['nodes'][0]]['token'].stdout }} {{ hostvars[groups.nodes[0]]['ansible_default_ipv4']['address'] }}"
      args:
        creates: /etc/kubernetes/kubelet.conf
      when: inventory_hostname != groups.nodes[0]

    # Master
    - name: kubectl apply weave
      command: kubectl apply -f https://git.io/weave-kube
      when: inventory_hostname == groups.nodes[0]

    - name: kubectl apply dashboard
      command: kubectl apply -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
      when: inventory_hostname == groups.nodes[0]

- name: Health check
  hosts: nodes
  tasks:
    - name: Wait for nodes registration
      shell: "/usr/bin/test $(kubectl get nodes -o name | wc -l) == {{ node_count }}"
      register: nodes_status
      retries: 30
      delay: 10
      until: nodes_status | success
      when: inventory_hostname == groups.nodes[0]

    - name: Get nodes
      command: kubectl get nodes
      when: inventory_hostname == groups.nodes[0]
      register: nodes

    - name: Display nodes
      debug:
        var: nodes.stdout_lines
      when: inventory_hostname == groups.nodes[0]

    - name: Get cluster info
      command: kubectl cluster-info
      when: inventory_hostname == groups.nodes[0]
      register: clusterinfo

    - name: Display cluster info
      debug:
        var: clusterinfo.stdout_lines
      when: inventory_hostname == groups.nodes[0]
