- name: Create master security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-master"
    state: present
  when: state == "present"

- name: Create nodes security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-nodes"
    state: present
  when: state == "present"

- name: Allow traffic to master from anywhere
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    remote_ip_prefix: 142.1.177.0/24
  when: state == "present"

- name: Allow SSH traffic to master
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: "{{ SSH_allowed_IP_space }}"
  when: state == "present"

- name: Allow traffic to 6443
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    protocol: tcp
    port_range_min: 6443 
    port_range_max: 6443
    remote_ip_prefix: "{{ allow_kube }}"
  when: state == "present"

- name: Allow traffic to master from nodes
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-master"
    remote_group: "sg-{{ name }}-nodes"
  when: state == "present"


- name: Allow traffic to nodes from anywhere
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_ip_prefix: 142.1.177.0/24
  when: state == "present"

- name: Allow traffic to nodes from nodes
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_group: "sg-{{ name }}-nodes"
  when: state == "present"

- name: Allow traffic to nodes from master
  tags: bootstrap
  os_security_group_rule:
    security_group: "sg-{{ name }}-nodes"
    remote_group: "sg-{{ name }}-master"
  when: state == "present"


- name: Delete master security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-master"
    state: absent
  when: state == "absent"

- name: Delete nodes security group
  tags: bootstrap
  os_security_group:
    name: "sg-{{ name }}-nodes"
    state: absent
  when: state == "absent"
