- name: Wait for nodes registration
  shell: "/usr/bin/test $(kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes | grep -ow Ready | wc -l) == {{ groups['nodes'] | length + groups['master'] | length }}"
  register: nodes_status
  retries: 30
  delay: 10
  until: nodes_status | success
  ignore_errors: yes

- name: Get event log
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf get events --all-namespaces
  register: events

- name: Display events
  debug:
    var: events.stdout_lines

- name: Get nodes
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes
  register: nodes

- name: Display nodes
  debug:
    var: nodes.stdout_lines

- name: Get cluster info
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf cluster-info
  register: clusterinfo

- name: Display cluster info
  debug:
    var: clusterinfo.stdout_lines

- name: Slurp kubectl configuration
  slurp:
    src: /etc/kubernetes/admin.conf
  register: kubectl_admin

- name: Save kubectl configuration in a fact
  set_fact:
    kubectl: "{{ kubectl_admin['content'] | b64decode | from_yaml }}"
