- name: Wait for nodes registration
  shell: "/usr/bin/test $(kubectl get nodes | grep -ow Ready | wc -l) == {{ groups['nodes'] | length + groups['master'] | length }}"
  register: nodes_status
  retries: 30
  delay: 10
  until: nodes_status | success
  ignore_errors: yes

- name: Get event log
  command: kubectl get events --all-namespaces
  register: events

- name: Display events
  debug:
    var: events.stdout_lines

- name: Get nodes
  command: kubectl get nodes
  register: nodes

- name: Display nodes
  debug:
    var: nodes.stdout_lines

- name: Get cluster info
  command: kubectl cluster-info
  register: clusterinfo

- name: Display cluster info
  debug:
    var: clusterinfo.stdout_lines
