- name: kubectl apply weave
  command: kubectl apply -f https://git.io/weave-kube-1.6

- name: kubectl apply dashboard
  command: kubectl apply -f https://rawgit.com/kubernetes/dashboard/master/src/deploy/kubernetes-dashboard.yaml
